name: Go build, test and send report to sonar

on:
  push:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  build:
    uses: netcracker/qubership-core-infra/.github/workflows/go-build-with-sonar.yaml@v1.0.1
    with:
      go-version: 1.23
      sonar-project-key: ${{ vars.SONAR_PROJECT_KEY }}
    secrets:
      sonar-token: ${{ secrets.SONAR_TOKEN }}